[package]
name = "dwbase-stream-local"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
dwbase-core = { path = "../dwbase-core" }
dwbase-engine = { path = "../dwbase-engine" }
