[package]
name = "dwbase-wit-host"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
dwbase-core = { path = "../dwbase-core" }
dwbase-engine = { path = "../dwbase-engine" }
serde.workspace = true
thiserror.workspace = true
wit-parser.workspace = true
